# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    # - id: check-ast  # file parses as valid Python
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict  # no <<<<
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    # - id: detect-aws-credentials
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: name-tests-test
    - id: trailing-whitespace
- repo: https://github.com/pypa/pip-audit
  rev: v2.7.3
  hooks:
    - id: pip-audit
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.7
  hooks:
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    # - id: ruff-format
ci:
  # Leave pip-audit to only run locally and not in CI
  # pre-commit.ci does not allow network calls
  skip: [ pip-audit ]
